spring:
  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: ecloudlink
#    password: 95938
    min-idle: 1
    max-active: 7
    max-wait: 10000
    initial-size: 1
    db-type: sqlserver
    filters: stat,slf4j
#    url: jdbc:sqlserver://172.16.4.99; DatabaseName=WMS
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
#  jpa:
#    database: sql_server
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy:
#    show-sql: true
